name: md_ui_kit
description: "Miracle Development UI Kit"
publish_to: "none"
version: 2.5.2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  storybook_flutter: ^0.14.1
  logger: ^2.1.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  flex_color_scheme: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  shaders:
    - shaders/gaussian_blur.frag
    - shaders/blurred_circle.frag

  assets:
    - assets/fonts/
    - assets/icons/logo/
    - assets/icons/initial_wave/
    - assets/icons/copy/
    - assets/icons/nav_bar/

  fonts:
    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf
        - asset: assets/fonts/Play-Bold.ttf
